config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_profile:
    dst: ~/.profile
    src: profile
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tmux.conf.local:
    dst: ~/.tmux.conf.local
    src: tmux.conf.local
profiles:
  develop:
    dotfiles:
    - f_bashrc
    - f_gitconfig
    - f_profile
    - f_tmux.conf
    - f_tmux.conf.local
